{
 "title": "Cloudflare Load Balancer Watcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(cloudflare_dns_record_name_info,domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "List of Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nodes_info{domain=\"$domain\"}"
    }
   ]
  },
  {
   "title": "HTTP response code from Cloudflare",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_dns_response_code{domain=\"$domain\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Last response time of monitored nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_response_time{domain=\"$domain\"}",
     "legendFormat": "{{node_ip}}"
    },
    {
     "expr": "node_check_timeout_seconds{domain=\"$domain\"}",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Cloudflare responce duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "cloudflare_dns_request_duration_seconds{domain=\"$domain\"}",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Status of monitored nodes",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time(node_status{domain=\"$domain\"}[$__interval])",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Number of hosts in Cloudflare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "cloudflare_dns_hosts_in_response{domain=\"$domain\"}",
     "legendFormat": "Numbers"
    }
   ]
  }
 ]
}